package com.yosep.msa.yosfrontserver.entity;

public enum ProductDetailType {
	// TOP
	SHORTSLEEV, LONGSLEEV, SLEEVELESS, SHIRTBLOUSE, PIKEKARA, MANTOMAN, HOOD, SWEATER,

	// OUTER
	MA1, SINGLECOAT, LEATHERJACKET, TRUKERJACKET, LONGPADDING, SUIT, PADDINGVEST,

	// BOTTOM
	DENIMPANTS, COTTONPANTS, SKIRT, SUITPANTS, TRAINING, LEGGINGS,
	
	// BAG
	BAGPACK, WAISTBAG, CROSSBAG, CLUTCH, ECOBAG, CARRIER,
	
	// SHOES
	CANVAS, SHOES, LOAFERS, BOOTS, BOATMOCHA, SANDLE, FLAT,
	
	// WATCH
	DIGITAL, ANALOG, QUIRTZ,
	
	// HEADWEAR
	CAB, FEDORA, BEANIE,
	
	// EYEWEAR
	GLASSES, SUNGLASSES
}
